SELECT
    DISTINCT(APP_ID),
    MAX(COLLECTOR_TSTAMP) AS LATEST_DATA,
    CURRENT_DATE,
    DATEDIFF(day, LATEST_DATA, CURRENT_DATE) AS DAYS_APART
FROM DATA_COLLECTION_DB.SNOWPLOW.BASE_EVENTS
WHERE EVENT = 'page_view'
GROUP BY APP_ID
ORDER BY MAX(COLLECTOR_TSTAMP) DESC